### ISSUE TITLE
Error downloading file https://github.com/kameshsampath/jo/examples/http/server.java: java.io.FileNotFoundException: /var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/kameshsampath-jo-examples-http/server.java (No such file or directory)

### ISSUE THREAD

**Issue by cmoulliard** [kameshsampath/jo#12]
## Issue

```
java -jar target/jo-runner.jar apply --file="$PWD/examples/kubernetes/deployment-jbang.yaml"
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-06-18 13:27:52,704 INFO  [io.quarkus] (main) jo 0.0.1-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.853s. Listening on: http://0.0.0.0:8080
2020-06-18 13:27:52,722 INFO  [io.quarkus] (main) Profile prod activated.
2020-06-18 13:27:52,722 INFO  [io.quarkus] (main) Installed features: [cdi, picocli, rest-client, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-fault-tolerance]
2020-06-18 13:27:54,096 INFO  [dev.kam.act.JBangImageBuilder] (main) Destination file /var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/kameshsampath-jo-examples-http/server.java
2020-06-18 13:27:54,097 ERROR [dev.kam.act.JBangImageBuilder] (main) Error downloading file https://github.com/kameshsampath/jo/examples/http/server.java: java.io.FileNotFoundException: /var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/kameshsampath-jo-examples-http/server.java (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
	at dev.kameshs.actions.JBangImageBuilder.downloadScriptFile(JBangImageBuilder.java:165)
	at dev.kameshs.actions.JBangImageBuilder.newBuild(JBangImageBuilder.java:66)
	at dev.kameshs.actions.JBangImageBuilder_ClientProxy.newBuild(JBangImageBuilder_ClientProxy.zig:157)
```
No folder `kameshsampath-jo-examples-http/` exists under `/var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T`

**Comment by kameshsampath** [comment]
it happened with snapshot builds but I need to wait for maven-resolver dep to be in Final to uupdate the project
